# Generated by Django 5.2.8 on 2025-11-28 13:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Contact', max_length=150, verbose_name='Titre principal')),
                ('intro_subtitle', models.TextField(blank=True, default='Un exemple de page contact avec un formulaire simple.', help_text="Ex : 'Un exemple de page contact avec un formulaire simple.'", verbose_name='Texte d’intro')),
                ('contact_email', models.EmailField(blank=True, default='contact@exemple.com', max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone')),
                ('contact_address', models.CharField(blank=True, default='Adresse de votre entreprise', max_length=255, verbose_name='Adresse')),
                ('contact_text', wagtail.fields.RichTextField(blank=True, default='', help_text='Ex : "Utilisez ce formulaire comme base..."', verbose_name='Texte au-dessus du formulaire')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormationsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Nos formations', max_length=150, verbose_name='Titre principal')),
                ('intro_subtitle', models.TextField(blank=True, default='Voici un exemple de section formations que vous pouvez adapter.', help_text="Ex : 'Voici un exemple de section formations...'", verbose_name='Texte d’intro')),
                ('formations', wagtail.fields.StreamField([('formation', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du formation', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le formation (format horizontal de préférence).', 'label': 'Image du formation', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, help_text='Liste complète des formations proposés.', verbose_name='formations')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='formations_preview',
            field=wagtail.fields.StreamField([('formation', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du formation', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le formation (format horizontal de préférence).', 'label': 'Image du formation', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, verbose_name='formations à afficher sur l’accueil (aperçu)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='formations_preview_intro',
            field=models.TextField(blank=True, default='Un aperçu rapide de nos formations.', help_text='Petite phrase pour introduire les formations.', verbose_name='Texte d’intro de la section formations (accueil)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='formations_preview_title',
            field=models.CharField(default='Nos formations', max_length=150, verbose_name='Titre de la section formations (accueil)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Grande image plein écran affichée en haut de la page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de fond du hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_kicker',
            field=models.CharField(blank=True, default='Bienvenue', help_text="Ex : 'Agence digitale · Exemple Wagtail'", max_length=150, verbose_name='Petit texte au-dessus du titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_page',
            field=models.ForeignKey(blank=True, help_text='Page vers laquelle le bouton principal redirige (ex : À propos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page du bouton principal'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_text',
            field=models.CharField(default='En savoir plus sur nous', max_length=50, verbose_name='Texte du bouton principal'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_page',
            field=models.ForeignKey(blank=True, help_text='Page vers laquelle le bouton secondaire redirige (ex : Contact).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page du bouton secondaire'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_text',
            field=models.CharField(blank=True, default='Discutons de votre projet', max_length=50, verbose_name='Texte du bouton secondaire'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Sous-titre de présentation pour la page d’accueil.', help_text='Quelques phrases qui expliquent le site.', verbose_name='Texte sous le titre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Titre de la page d’accueil', help_text="Ex : 'Créez un site vitrine moderne, clair et efficace.'", max_length=200, verbose_name='Titre principal'),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='À propos', max_length=150, verbose_name='Titre principal')),
                ('intro_subtitle', models.TextField(blank=True, default='En savoir plus sur nous.', help_text='Une petite phrase pour introduire la page.', verbose_name='Texte d’intro')),
                ('body', wagtail.fields.RichTextField(blank=True, default='', help_text='Contenu principal : histoire, mission, valeurs...', verbose_name='Texte de présentation')),
                ('image_caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Légende de l’image')),
                ('image', models.ForeignKey(blank=True, help_text='Photo d’équipe ou image illustrative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de la section À propos')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
